CREATE DATABASE SisPoupo;
USE SisPoupo; 

DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(100) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    TIP_USUARIO VARCHAR(50) NOT NULL UNIQUE, 
    CPF VARCHAR(11) NOT NULL UNIQUE, -- UNIQUE para garantir que não haja duplicidade de CPF
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    SITUACAO_CADASTRAL TINYINT NOT NULL DEFAULT 1,  -- 1 - Ativo | 0 - Inativo
    DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USUARIOS (NOME_USUARIO, NOME, TIP_USUARIO, CPF, TELEFONE, EMAIL, SENHA, SITUACAO_CADASTRAL) 
VALUES ('SisPoupo', 'Usuario Teste','USUARIO_PADRAO', '00000000000','00000000', 'sispoupo@gmail.com', '123456', 1);